server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'user'
    url: jdbc:postgresql://127.0.0.1:5432/customer
    password: 'password'
  jpa:
      hibernate:
          ddl-auto: create-drop
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
              format_sql: true
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true